flower-project-2024/WHOA_Server

- .gitignore
- build.gradle
- src/main/java/com/whoa/whoaserver/flower/service/S3Uploader.java
- src/main/java/com/whoa/whoaserver/global/config/S3Config.java
- src/main/java/com/whoa/whoaserver/global/config/SwaggerConfig.java
- src/main/java/com/whoa/whoaserver/global/exception/BadRequestException.java
- src/main/java/com/whoa/whoaserver/global/exception/ExceptionCode.java
- src/main/java/com/whoa/whoaserver/global/exception/ExceptionResponse.java
- src/main/java/com/whoa/whoaserver/global/exception/GlobalExceptionHandler.java
- src/main/resources/application.yml
기본 인프라 설정 @dudrhy12 @rla124 
> #2 
- yml 파일 설정
- Exception 설정
- S3 Config 작성
- Swagger Config 작성 -> 담당 : @rla124 
- application-rds, application-credentials.yml 파일 작성 후 노션에 공유 -> 담당 : @rla124
> [Infra] Basic setting

- src/main/java/com/whoa/whoaserver/TempController.java
- src/main/java/com/whoa/whoaserver/member/controller/MemberController.java
- src/main/java/com/whoa/whoaserver/member/domain/Member.java
- src/main/java/com/whoa/whoaserver/member/domain/MemberRepository.java
- src/main/java/com/whoa/whoaserver/member/dto/request/MemberRegisterRequest.java
- src/main/java/com/whoa/whoaserver/member/dto/response/MemberInfo.java
- src/main/java/com/whoa/whoaserver/member/service/MemberService.java
디바이스 별 memberId 구분을 위한 API 개발 
> close #4 
- swagger tag 이용하여 확인 가능
- 멤버 등록 시 백엔드 단에서 에러처리 완료
> [Feat] 멤버 등록

- .gitignore
- src/main/java/com/whoa/whoaserver/flower/controller/FlowerController.java
- src/main/java/com/whoa/whoaserver/flower/domain/Flower.java
- src/main/java/com/whoa/whoaserver/flower/dto/FlowerResponseDto.java
- src/main/java/com/whoa/whoaserver/flower/repository/FlowerRepository.java
- src/main/java/com/whoa/whoaserver/flower/service/FlowerService.java
- src/main/java/com/whoa/whoaserver/flowerExpression/domain/FlowerExpression.java
- src/main/java/com/whoa/whoaserver/flowerExpression/dto/FlowerExpressionResponseDto.java
- src/main/java/com/whoa/whoaserver/flowerLanguageAndColor/domain/FlowerLanguageAndColor.java
- src/main/java/com/whoa/whoaserver/keyword/domain/Keyword.java
꽃 상세조회 API 개발
> #6 
- flower, flowerExpression Domain/Respository 생성
- ResponseDto 생성
- Service 개발
- Controller 개발
- DB에 이미지 파일 주소를 삽입하기 어려우므로, 이미지 파일 주소를 S3 bucket에서 읽어오는 기능 개발 고려
> Feat: 꽃 조회 API 개발

- src/main/java/com/whoa/whoaserver/flower/domain/Flower.java
- src/main/java/com/whoa/whoaserver/flower/dto/FlowerResponseDto.java
꽃 상세조회 API 수정
> #6 
- Flower Entity Field 수정
- 보관법, 관리법은 \n으로 구분하여 하나의 String으로 저장
> [Fix] 꽃상세조회 Entity 수정

- src/main/java/com/whoa/whoaserver/flower/controller/FlowerController.java
- src/main/java/com/whoa/whoaserver/flower/domain/Flower.java
- src/main/java/com/whoa/whoaserver/flower/repository/FlowerRepository.java
- src/main/java/com/whoa/whoaserver/flower/service/FlowerService.java
오늘의꽃 조회 API
> #11 
- 추천날짜 field 추가
- 오늘의꽃 조회 Controller
- 오늘의꽃 조회 Service
- 오늘의꽃 조회 Repository
> [Feat] 오늘의꽃 조회 API

- src/main/java/com/whoa/whoaserver/member/domain/Member.java
- src/main/java/com/whoa/whoaserver/member/service/MemberService.java
register API 로직 수정
close #29 
(기존 request, response dto에 대한 수정 없음) 
(entity, service 단에서의 수정만 존재, 200ok 및 예외 처리 postman으로 확인 완료)
(DB 추가 확인 완료)
> [Refact] 멤버 등록 API 리팩토링

- .gitignore
- build.gradle
- src/main/java/com/whoa/whoaserver/crawl/FlowerCrawlerScheduler.java
- src/main/java/com/whoa/whoaserver/crawl/controller/FlowerRankingController.java
- src/main/java/com/whoa/whoaserver/crawl/domain/FlowerRanking.java
- src/main/java/com/whoa/whoaserver/crawl/dto/FlowerRankingResponseDto.java
- src/main/java/com/whoa/whoaserver/crawl/repository/FlowerRankingRepository.java
- src/main/java/com/whoa/whoaserver/crawl/service/FlowerCrawlerScheduler.java
- src/main/java/com/whoa/whoaserver/crawl/service/FlowerRankingService.java
- src/main/java/com/whoa/whoaserver/flower/controller/FlowerController.java
- src/main/java/com/whoa/whoaserver/flower/repository/FlowerRepository.java
- src/main/resources/application.yml
- src/test/java/com/whoa/whoaserver/FlowerCrawlerSchedulerTest.java
저렴한 꽃 조회 API 개발
- #28 
IP 주소에 따라 크롤링 서비스 코드가 다름
> Feat: 저렴한 꽃 조회 API

- .gitignore
- src/main/java/com/whoa/whoaserver/flower/controller/FlowerController.java
백엔드 민감 정보 분리 이후 CICD 배포 자동화를 위해 springboot 동기화
> application-crawl.yml 추가 후 CICD 배포를 위한 수정

- src/main/java/com/whoa/whoaserver/bouquet/domain/Bouquet.java
- src/main/java/com/whoa/whoaserver/bouquet/domain/BouquetImage.java
- src/main/java/com/whoa/whoaserver/bouquet/domain/BouquetRepository.java
- src/main/java/com/whoa/whoaserver/bouquet/dto/request/BouquetCustomizingRequest.java
- src/main/java/com/whoa/whoaserver/bouquet/dto/request/PresignedUrlRequest.java
- src/main/java/com/whoa/whoaserver/bouquet/dto/response/BouquetCustomizingResponse.java
- src/main/java/com/whoa/whoaserver/bouquet/dto/response/BouquetInfoDetailResponse.java
- src/main/java/com/whoa/whoaserver/bouquet/dto/response/BouquetOrderResponse.java
- src/main/java/com/whoa/whoaserver/bouquet/service/BouquetCustomizingService.java
- src/main/java/com/whoa/whoaserver/bouquet/service/BouquetImageService.java
- src/main/java/com/whoa/whoaserver/global/exception/ExceptionCode.java
주문서 별 다수의 이미지 경로 반환으로 수정
close #36 
close #40 
코드 리펙토링
> [Refact] 이미지 파일명 중복 예외 처리 및 이미지 반환 로직 수정

- .gitignore
- src/main/java/com/whoa/whoaserver/crawl/domain/FlowerRanking.java
- src/main/java/com/whoa/whoaserver/crawl/dto/FlowerRankingResponseDto.java
- src/main/java/com/whoa/whoaserver/crawl/service/FlowerRankingService.java
- src/main/java/com/whoa/whoaserver/flower/controller/FlowerController.java
> Fix: 저렴한 꽃 순위 로직 및 오타 수정

- .gitignore
- src/main/java/com/whoa/whoaserver/crawl/domain/FlowerRanking.java
- src/main/java/com/whoa/whoaserver/crawl/dto/FlowerRankingResponseDto.java
- src/main/java/com/whoa/whoaserver/crawl/service/FlowerRankingService.java
- src/main/java/com/whoa/whoaserver/flower/controller/FlowerController.java
> Fix: 저렴한 꽃 순위 API 수정

- src/main/java/com/whoa/whoaserver/flower/dto/FlowerRecommandResponseDto.java
- src/main/java/com/whoa/whoaserver/flower/service/FlowerService.java
오늘의 꽃 API 중 ResponseDto 생성 및 Service 코드 수정
> Fix: 오늘의꽃 ResponseDto 수정

- src/main/java/com/whoa/whoaserver/bouquet/domain/Bouquet.java
- src/main/java/com/whoa/whoaserver/bouquet/dto/request/BouquetCustomizingRequest.java
- src/main/java/com/whoa/whoaserver/bouquet/dto/response/BouquetInfoDetailResponse.java
- src/main/java/com/whoa/whoaserver/bouquet/dto/response/BouquetOrderResponse.java
- src/main/java/com/whoa/whoaserver/bouquet/service/BouquetCustomizingService.java
- src/main/java/com/whoa/whoaserver/global/common/BaseEntity.java
- src/main/java/com/whoa/whoaserver/global/config/JpaAuditingConfig.java
프론트 요구 사항 반영
- createAt 추가 후 resonse DTO에 반영
- entity attribute 중 default value 처리
- response DTO 형식 변경 : 요구서 상세 조회 시 flowerInfoList 항목 구조화
close #53
> [Refact] Entity attribute && Response DTO 수정

- src/main/java/com/whoa/whoaserver/flower/domain/Flower.java
- src/main/java/com/whoa/whoaserver/flower/dto/FlowerRecommandResponseDto.java
- src/main/java/com/whoa/whoaserver/flower/dto/FlowerResponseDto.java
> [Fix] Flower Entity 수정

- src/main/java/com/whoa/whoaserver/flower/domain/Flower.java
- src/main/java/com/whoa/whoaserver/flower/dto/FlowerRecommandResponseDto.java
- src/main/java/com/whoa/whoaserver/flower/dto/FlowerResponseDto.java
> [Fix] Flower 엔티티 수정

- src/main/java/com/whoa/whoaserver/bouquet/dto/response/BouquetInfoDetailResponse.java
- src/main/java/com/whoa/whoaserver/crawl/service/FlowerRankingService.java
- src/main/java/com/whoa/whoaserver/flower/domain/Flower.java
- src/main/java/com/whoa/whoaserver/flower/dto/FlowerRecommandResponseDto.java
- src/main/java/com/whoa/whoaserver/flower/dto/FlowerResponseDto.java
- src/main/java/com/whoa/whoaserver/keyword/service/FlowerKeywordService.java
> Fix: Modify Flower entity

- src/main/java/com/whoa/whoaserver/bouquet/dto/response/BouquetInfoDetailResponse.java
- src/main/java/com/whoa/whoaserver/crawl/service/FlowerRankingService.java
- src/main/java/com/whoa/whoaserver/flower/domain/Flower.java
- src/main/java/com/whoa/whoaserver/flower/dto/FlowerRecommandResponseDto.java
- src/main/java/com/whoa/whoaserver/flower/dto/FlowerResponseDto.java
- src/main/java/com/whoa/whoaserver/keyword/service/FlowerKeywordService.java
> Fix: Flower Entity 수정

- src/main/java/com/whoa/whoaserver/flower/controller/FlowerController.java
- src/main/java/com/whoa/whoaserver/flower/domain/Flower.java
- src/main/java/com/whoa/whoaserver/flower/dto/FlowerRecommendResponseDto.java
- src/main/java/com/whoa/whoaserver/flower/dto/FlowerRequestDto.java
- src/main/java/com/whoa/whoaserver/flower/service/FlowerService.java
- src/main/java/com/whoa/whoaserver/flower/service/S3Uploader.java
> Feat: 꽃 이미지 등록 API

- src/main/java/com/whoa/whoaserver/flower/repository/FlowerRepository.java
- src/main/java/com/whoa/whoaserver/keyword/service/FlowerKeywordService.java
- 키워드별 꽃 조회에서 쿼리 수를 감소시킴
close #42
> [Refact] 키워드별 꽃 조회 쿼리 성능 향상

- .github/workflows/main.yml
실제 배포 및 운영 시 prod 환경에서 실행되도록 변경
close #66
> [CICD] git action을 통해 application-prod.yml로 빌드하여 배포되도록 수정

- src/main/java/com/whoa/whoaserver/bouquet/domain/BouquetRepository.java
- src/main/java/com/whoa/whoaserver/bouquet/repository/BouquetImageRepository.java
- src/main/java/com/whoa/whoaserver/bouquet/repository/BouquetRepository.java
- src/main/java/com/whoa/whoaserver/bouquet/service/BouquetCustomizingService.java
- src/main/java/com/whoa/whoaserver/bouquet/service/BouquetImageService.java
- src/main/java/com/whoa/whoaserver/global/exception/ExceptionCode.java
이슈에 세부적으로 설명(프론트에서는 팝업창 띄우는 방식으로)
close #68
> Fix: 꽃다발 커스터마이징 네이밍 중복 예외 처리 추가

- .github/workflows/main.yml
> [CICD] DEV, PROD 완벽하게 분리

- src/main/java/com/whoa/whoaserver/bouquet/controller/BouquetCustomizingController.java
- src/main/java/com/whoa/whoaserver/bouquet/controller/BouquetImageController.java
- src/main/java/com/whoa/whoaserver/global/exception/GlobalExceptionHandler.java
> [Fix] @ExceptionHandler 400 bad request response parameter && request DTO null mapping

- src/main/java/com/whoa/whoaserver/bouquet/controller/BouquetImageController.java
- src/main/java/com/whoa/whoaserver/bouquet/dto/request/MultipartFileUploadRequest.java
- src/main/java/com/whoa/whoaserver/bouquet/dto/response/MultipartFileUploadedUrlResponse.java
- src/main/java/com/whoa/whoaserver/bouquet/service/BouquetImageService.java
- src/main/java/com/whoa/whoaserver/global/config/S3Config.java
- src/main/java/com/whoa/whoaserver/global/exception/ExceptionCode.java
> [Feat] 한 번의 API 호출로 여러 이미지 동시 업로드 구현

- src/main/java/com/whoa/whoaserver/bouquet/dto/response/BouquetInfoDetailResponse.java
- src/main/java/com/whoa/whoaserver/bouquet/service/BouquetCustomizingService.java
- src/main/java/com/whoa/whoaserver/keyword/service/FlowerKeywordService.java
> [Refact] stream 불변성 보장하도록 수정

- src/main/java/com/whoa/whoaserver/keyword/dto/response/FlowerInfoByKeywordResponse.java
- src/main/java/com/whoa/whoaserver/keyword/service/FlowerKeywordService.java
- src/main/java/com/whoa/whoaserver/mapping/repository/FlowerExpressionKeywordRepository.java
> [Fix] 키워드 별 꽃 조회 매핑 테이블 기반 로직 수정 완료

- build.gradle
- src/main/java/com/whoa/whoaserver/bouquet/controller/BouquetImageController.java
- src/main/java/com/whoa/whoaserver/bouquet/service/BouquetImageService.java
- src/main/java/com/whoa/whoaserver/global/config/S3Config.java
- src/main/java/com/whoa/whoaserver/global/exception/ExceptionCode.java
> [Fix] 다중 이미지 업로드 최종 완료

- build.gradle
- src/main/java/com/whoa/whoaserver/global/config/QuerydslConfig.java
- src/main/java/com/whoa/whoaserver/keyword/service/FlowerKeywordService.java
- src/main/java/com/whoa/whoaserver/mapping/repository/FlowerExpressionKeywordRepository.java
- src/main/java/com/whoa/whoaserver/mapping/repository/FlowerExpressionKeywordRepositoryCustom.java
- src/main/java/com/whoa/whoaserver/mapping/repository/FlowerExpressionKeywordRepositoryImpl.java
> [Refact] 키워드별 꽃 조회 Querydsl 적용

- src/main/java/com/whoa/whoaserver/crawl/domain/FlowerRanking.java
- src/main/java/com/whoa/whoaserver/crawl/service/FlowerCrawlerScheduler.java
- src/main/java/com/whoa/whoaserver/crawl/service/FlowerRankingService.java
- src/main/java/com/whoa/whoaserver/flower/service/FlowerService.java
- src/test/java/com/whoa/whoaserver/FlowerCrawlerSchedulerTest.java
- 저렴한꽃 API 수정 : 크롤링 안되는 문제 해결 (Date형식이 잘못되었었음)
- 오늘의꽃 API 수정 : 하루에 하나의 꽃만 반환되도록 로직 수정
#96
- 저렴한꽃 Response 중 꽃의 한줄소개 vs 꽃말 vs 키워드 중 어떤 것을 보낼 것인지 논의 필요
> [Fix] 저렴한꽃/오늘의꽃 API 수정

- src/main/java/com/whoa/whoaserver/crawl/domain/FlowerRanking.java
- src/main/java/com/whoa/whoaserver/crawl/service/FlowerCrawlerScheduler.java
- src/main/java/com/whoa/whoaserver/crawl/service/FlowerRankingService.java
- src/main/java/com/whoa/whoaserver/flower/service/FlowerService.java
- src/test/java/com/whoa/whoaserver/FlowerCrawlerSchedulerTest.java
- 저렴한꽃 API 수정 : 크롤링 안되는 문제 해결 (Date형식이 잘못되었었음)
- 오늘의꽃 API 수정 : 하루에 하나의 꽃만 반환되도록 로직 수정
#96
- 저렴한꽃 Response 중 꽃의 한줄소개 vs 꽃말 vs 키워드 중 어떤 것을 보낼 것인지 논의 필요
> [Fix] 오늘의꽃/저렴한꽃 API 수정

- src/main/java/com/whoa/whoaserver/keyword/service/FlowerKeywordService.java
> [Fix] 키워드별 꽃 전체 조회 중복 데이터 처리

- src/main/java/com/whoa/whoaserver/bouquet/controller/BouquetImageController.java
- src/main/java/com/whoa/whoaserver/bouquet/domain/Bouquet.java
- src/main/java/com/whoa/whoaserver/bouquet/domain/type/ColorTypeOption.java
- src/main/java/com/whoa/whoaserver/bouquet/domain/type/FlowerSubstitutionTypeOption.java
- src/main/java/com/whoa/whoaserver/bouquet/dto/request/BouquetCustomizingRequest.java
- src/main/java/com/whoa/whoaserver/bouquet/repository/BouquetRepository.java
- src/main/java/com/whoa/whoaserver/bouquet/repository/BouquetRepositoryCustom.java
- src/main/java/com/whoa/whoaserver/bouquet/repository/BouquetRepositoryImpl.java
- src/main/java/com/whoa/whoaserver/bouquet/service/BouquetImageService.java
- src/main/java/com/whoa/whoaserver/global/config/S3Config.java
- src/main/java/com/whoa/whoaserver/global/exception/ExceptionCode.java
> [Perf] 다중 이미지 업로드 로직 개선

- src/main/java/com/whoa/whoaserver/bouquet/dto/response/BouquetInfoDetailResponse.java
> [Feat] bouquet 단건 조회 예외 처리 추가 맟 응답 수정

- src/main/java/com/whoa/whoaserver/bouquet/controller/BouquetImageController.java
- src/main/java/com/whoa/whoaserver/bouquet/domain/BouquetImage.java
- src/main/java/com/whoa/whoaserver/bouquet/dto/response/BouquetInfoDetailResponse.java
- src/main/java/com/whoa/whoaserver/bouquet/service/BouquetImageService.java
- src/main/java/com/whoa/whoaserver/global/config/S3Config.java
- src/main/java/com/whoa/whoaserver/global/exception/ExceptionCode.java
close #115 
삭제 성공 시 204 코드 반환
수정 성공 시 200 코드 반환
포스트맨 확인 완료
> [Feat] S3 이미지 단건 수정 및 삭제, 예외 처리

- src/main/java/com/whoa/whoaserver/bouquet/service/BouquetCustomizingService.java
> [Feat]  bouquet 전체 조회 시 bouquetImageList가 아니라 선택한 첫 번째 꽃 사진을 반환

- .github/workflows/main.yml
- Dockerfile
- build.gradle
- src/main/resources/application-actuator.yml
- src/main/resources/application.yml
> [Chore] SpringBoot Actuator

- build.gradle
- src/main/java/com/whoa/whoaserver/global/config/CacheConfig.java
- src/main/java/com/whoa/whoaserver/global/config/type/CacheType.java
- src/main/java/com/whoa/whoaserver/keyword/service/FlowerKeywordService.java
> [Perf] 키워드별 꽃 조회 API 개선

- src/main/java/com/whoa/whoaserver/bouquet/domain/BouquetImage.java
- src/main/java/com/whoa/whoaserver/bouquet/dto/response/BouquetInfoDetailResponse.java
- src/main/java/com/whoa/whoaserver/member/domain/Member.java
- src/main/java/com/whoa/whoaserver/member/domain/MemberRepository.java
> [Refact] 일부 엔티티 칼럼 조정 및 불필요한 코드 삭제

- src/main/java/com/whoa/whoaserver/bouquet/service/BouquetCustomizingService.java
- src/main/java/com/whoa/whoaserver/member/domain/Member.java
- src/main/java/com/whoa/whoaserver/member/dto/request/MemberRegisterRequest.java
- src/main/java/com/whoa/whoaserver/member/repository/MemberRepository.java
- src/main/java/com/whoa/whoaserver/member/service/MemberService.java
- src/test/java/com/whoa/whoaserver/member/controller/MemberControllerTest.java
- src/test/java/com/whoa/whoaserver/member/repository/MemberRepositoryTest.java
- src/test/java/com/whoa/whoaserver/member/service/MemberServiceTest.java
> [Test] 디바이스 기기 등록 테스트 코드 작성 완료

- src/main/java/com/whoa/whoaserver/bouquet/controller/BouquetCustomizingController.java
- src/main/java/com/whoa/whoaserver/bouquet/controller/BouquetCustomizingControllerV2.java
- src/main/java/com/whoa/whoaserver/bouquet/domain/Bouquet.java
- src/main/java/com/whoa/whoaserver/bouquet/domain/type/BouquetStatus.java
- src/main/java/com/whoa/whoaserver/bouquet/dto/response/BouquetOrderResponse.java
- src/main/java/com/whoa/whoaserver/bouquet/repository/BouquetRepository.java
- src/main/java/com/whoa/whoaserver/bouquet/service/BouquetCustomizingService.java
- src/main/java/com/whoa/whoaserver/bouquet/service/BouquetCustomizingServiceV2.java
close #134 
- 커밋 내역에서 확인 가능
리펙토링 필요
> [Feat] bouquet 제작 완료 API, 제작 여부 구별, 전체 조회 시 나눠서 반환

- src/main/java/com/whoa/whoaserver/bouquet/controller/BouquetCustomizingControllerV2.java
- src/main/java/com/whoa/whoaserver/bouquet/controller/BouquetImageControllerV2.java
- src/main/java/com/whoa/whoaserver/bouquet/dto/response/RealBouquetImageResponse.java
- src/main/java/com/whoa/whoaserver/bouquet/service/BouquetCustomizingServiceV2.java
- src/main/java/com/whoa/whoaserver/bouquet/service/BouquetImageServiceV2.java
> [Feat] bouquetImage 등록 및 전체 조회 시 조건에 따른 flowerImage, bouquetImage 분기 처리

- src/main/java/com/whoa/whoaserver/bouquet/controller/BouquetCustomizingControllerV2.java
- src/main/java/com/whoa/whoaserver/bouquet/domain/Bouquet.java
- src/main/java/com/whoa/whoaserver/bouquet/dto/response/BouquetOrderResponseV2.java
- src/main/java/com/whoa/whoaserver/bouquet/dto/response/RealBouquetImageResponse.java
- src/main/java/com/whoa/whoaserver/bouquet/service/BouquetCustomizingServiceV2.java
- src/main/java/com/whoa/whoaserver/bouquet/service/BouquetImageServiceV2.java
> [Refact] bouquet 전체 조회 시 bouquet 실제 이미지 등록 여부 처리 문제 해결

- src/main/java/com/whoa/whoaserver/bouquet/controller/BouquetCustomizingControllerV2.java
- src/main/java/com/whoa/whoaserver/bouquet/dto/response/BouquetInfoDetailResponseV2.java
- src/main/java/com/whoa/whoaserver/bouquet/service/BouquetCustomizingServiceV2.java
> [Feat] bouquet 상세 조회 시 선택한 꽃에 대한 id와 keyword 추가 반환

- .gitignore
- src/main/java/com/whoa/whoaserver/global/config/type/CacheType.java
- src/main/java/com/whoa/whoaserver/keyword/domain/Keyword.java
- src/main/java/com/whoa/whoaserver/keyword/service/FlowerKeywordServiceV2.java
- src/main/java/com/whoa/whoaserver/mapping/domain/CustomizingPurposeKeyword.java
- src/main/java/com/whoa/whoaserver/mapping/domain/FlowerExpressionKeyword.java
> [Perf] 구매 목적을 고려한 키워드별 꽃 조회 API 개선

- src/main/java/com/whoa/whoaserver/flower/dto/FlowerResponseDto.java
- src/main/java/com/whoa/whoaserver/flower/service/FlowerService.java
- src/main/java/com/whoa/whoaserver/flowerExpression/dto/FlowerExpressionResponseDto.java
- src/main/java/com/whoa/whoaserver/keyword/dto/response/FlowerInfoByKeywordResponse.java
- 꽃 상세 조회 API Response 수정
#152
> Fix: 꽃 상세 조회 API Response 수정

- src/main/java/com/whoa/whoaserver/flower/dto/FlowerResponseDto.java
- src/main/java/com/whoa/whoaserver/flower/service/FlowerService.java
- src/main/java/com/whoa/whoaserver/flowerExpression/dto/FlowerExpressionResponseDto.java
- src/main/java/com/whoa/whoaserver/keyword/dto/response/FlowerInfoByKeywordResponse.java
- 꽃 상세 조회 API Response 수정
#152
> Fix: 꽃 상세 조회 API Response 수정 - 배포

- src/main/java/com/whoa/whoaserver/WhoaserverApplication.java
- src/main/java/com/whoa/whoaserver/crawl/dto/FlowerRankingResponseDto.java
- src/main/java/com/whoa/whoaserver/crawl/repository/FlowerRankingRepository.java
- src/main/java/com/whoa/whoaserver/crawl/repository/FlowerRankingRepositoryCustom.java
- src/main/java/com/whoa/whoaserver/crawl/repository/FlowerRankingRepositoryImpl.java
- src/main/java/com/whoa/whoaserver/crawl/service/FlowerCrawlerScheduler.java
- src/main/java/com/whoa/whoaserver/crawl/service/FlowerRankingService.java
> [Perf] 공공데이터 스케쥴러 및 랭킹 조회 개선

- src/main/java/com/whoa/whoaserver/domain/bouquet/domain/Bouquet.java
- src/main/java/com/whoa/whoaserver/domain/bouquet/service/BouquetCustomizingServiceV2.java
- src/main/java/com/whoa/whoaserver/domain/flowerExpression/service/FlowerExpressionService.java
- src/main/java/com/whoa/whoaserver/global/config/type/CacheType.java
> [Pref] bouquet 전체 조회 개선

- src/main/java/com/whoa/whoaserver/domain/flower/repository/FlowerRepository.java
- src/main/java/com/whoa/whoaserver/domain/flower/service/FlowerService.java
> [Perf] 날짜에 대응되는 꽃 추천이 불가능할 경우 로직 개선

- src/main/java/com/whoa/whoaserver/domain/flowerExpression/repository/FlowerExpressionRepository.java
> [Perf] flowerExpression -> flowerImage 개선

- src/main/java/com/whoa/whoaserver/domain/flower/repository/FlowerRepository.java
- src/main/java/com/whoa/whoaserver/domain/flower/repository/FlowerRepositoryCustom.java
- src/main/java/com/whoa/whoaserver/domain/flower/repository/FlowerRepositoryImpl.java
> [Refact] 꽃 추천 로직 랜덤성 개선

- src/main/java/com/whoa/whoaserver/domain/flower/domain/FlowerRanking.java
- src/main/java/com/whoa/whoaserver/scheduler/FlowerCrawlerScheduler.java
- src/main/java/com/whoa/whoaserver/scheduler/FlowerRankingUpdater.java
> [Fix] 스케쥴러가 주기대로 실행되지 않는 현상 해결

- build.gradle
- src/main/java/com/whoa/whoaserver/domain/flower/domain/FlowerRanking.java
- src/main/java/com/whoa/whoaserver/domain/flower/repository/ranking/FlowerRankingRepository.java
- src/main/java/com/whoa/whoaserver/scheduler/FlowerCrawlerScheduler.java
- src/main/java/com/whoa/whoaserver/scheduler/FlowerRankingUpdater.java
- src/main/java/com/whoa/whoaserver/scheduler/dto/WebClientResponse.java
closed #173 -> 외부 API 통신 방식 개선
closed #180 -> 외부 API response 200 null일 경우 별도로 로직 추가하여 스케쥴러 기능 추가 및 성능 개선
> [Perf] 스케쥴러 작동 방식 및 전반적인 성능 개선

- src/main/java/com/whoa/whoaserver/domain/bouquet/domain/Bouquet.java
- src/main/java/com/whoa/whoaserver/domain/bouquet/domain/BouquetImage.java
- src/main/java/com/whoa/whoaserver/domain/bouquet/service/BouquetCustomizingServiceV2.java
- src/main/java/com/whoa/whoaserver/domain/member/domain/Member.java
jackson objectMapper 에러 해결
closed #218
> [Fix] 직렬화 문제 해결

- build.gradle
- src/main/java/com/whoa/whoaserver/domain/flower/repository/ranking/FlowerPopularityRepository.java
- src/main/java/com/whoa/whoaserver/scheduler/FlowerPopularityScheduler.java
flowerPopularity entity에 새로운 flowerId가 insert 되어야 하는 상황일 경우 null 체크 추가
closed #217
> [Fix] 새로운 flowerId가 선택되었을 때 인기 꽃 랭킹에 반영
